---
#ansy playbook start with three dash
-
###this minus in yaml indicate a list of items. the play contains a list of play
  hosts: node1
  vars:
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.64/bin/apache-tomcat-9.0.64.tar.gz
    tomcat_download_location: /usr/share/tomcat/apache-tomcat-9.0.64.tar.gz
  
  tasks:
    - name: install java 
      apt:
        name: default-jre
        state: present 